# Generated by Django 5.1.2 on 2024-10-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basesettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('facebook', models.URLField(verbose_name='Cыллка на facebook')),
                ('github', models.URLField(verbose_name='Cыллка на github')),
                ('twitter', models.URLField(verbose_name='Cыллка на twitter')),
                ('google', models.URLField(verbose_name='Cыллка на google')),
            ],
            options={
                'verbose_name': 'Основная настройка сайта',
                'verbose_name_plural': 'Оснавные настройки сайта',
            },
        ),
    ]
